In [8]:
# 이미지증식기
from keras.preprocessing.image import load_img
from keras.preprocessing.image import img_to_array, ImageDataGenerator
import matplotlib.pyplot as plt
import numpy as np
# 다중분류
from keras.models import Sequential, Input, Model
from keras.layers import Dense, Dropout, Flatten
from keras.layers import Conv2D, MaxPooling2D
from keras.layers.normalization import BatchNormalization
from keras.layers.advanced_activations import LeakyReLU

In [9]:
######################### 도형 다중 분류기 제작 with CNN #########################

# 트레인데이터
trainDatagen = ImageDataGenerator(rescale=1./225) # 이미지 증식기
trainGenerator = trainDatagen.flow_from_directory('손글씨데이터/train', target_size=(24,24), 
                                                            batch_size=3, 
                                                            class_mode='categorical')
# 테스트 데이터
testDatagen = ImageDataGenerator(rescale=1./225) # 이미지 증식기
testGenerator = testDatagen.flow_from_directory('손글씨데이터/test', target_size=(24,24), 
                                                            batch_size=3, 
                                                            class_mode='categorical')

Found 45 images belonging to 3 classes.
Found 15 images belonging to 3 classes.


In [10]:
# CNN모델구성
model = Sequential()
model.add(Conv2D(32, kernel_size = (3,3),
                    activation = 'relu',
                    input_shape = (24,24,3)))
model.add(Conv2D(64, kernel_size = (3,3),
                    activation = 'relu'))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Flatten())
model.add(Dense(128, activation='relu'))
model.add(Dense(3, activation='softmax'))

In [11]:
# 모델 학습 환경 설정
model.compile(loss="categorical_crossentropy",
                optimizer="adam",
                metrics=['accuracy'])

# 모델 학습
model.fit_generator(trainGenerator,     # 훈련데이터셋을 제공할 제너레이터
                    steps_per_epoch=15,
                    epochs=50,
                    validation_data=testGenerator,
                    validation_steps=5)   # 1에폭당 스텝 수

Instructions for updating:
Please use Model.fit, which supports generators.
Epoch 1/50
15/15 [==============================] - 0s 20ms/step - loss: 0.7397 - accuracy: 0.7333 - val_loss: 0.2471 - val_accuracy: 0.9333
Epoch 2/50
15/15 [==============================] - 0s 10ms/step - loss: 0.0673 - accuracy: 1.0000 - val_loss: 0.0801 - val_accuracy: 0.9333
Epoch 3/50
15/15 [==============================] - 0s 10ms/step - loss: 0.0071 - accuracy: 1.0000 - val_loss: 0.1194 - val_accuracy: 0.9333
Epoch 4/50
15/15 [==============================] - 0s 11ms/step - loss: 0.0036 - accuracy: 1.0000 - val_loss: 0.0263 - val_accuracy: 1.0000
Epoch 5/50
15/15 [==============================] - 0s 11ms/step - loss: 0.0014 - accuracy: 1.0000 - val_loss: 0.0251 - val_accuracy: 1.0000
Epoch 6/50
15/15 [==============================] - 0s 10ms/step - loss: 2.1174e-04 - accuracy: 1.0000 - val_loss: 0.0280 - val_accuracy: 1.0000
Epoch 7/50
15/15 [==============================] - 0s 10ms/step - loss: 1

In [12]:
# 모델평가
scores = model.evaluate_generator(testGenerator, steps=5)
print("정확도: ",round(scores[1]*100, 1),"%")

Instructions for updating:
Please use Model.evaluate, which supports generators.
정확도:  100.0 %


In [13]:
# 모델 사용
output = model.predict_generator(testGenerator, steps=5)
print(testGenerator.class_indices)
print(output)

Instructions for updating:
Please use Model.predict, which supports generators.
{'circle': 0, 'rectangle': 1, 'triangle': 2}
[[9.9741673e-01 1.2543708e-05 2.5708214e-03]
 [3.3214346e-06 9.9999666e-01 9.5853457e-11]
 [2.2894616e-07 7.5956335e-09 9.9999976e-01]
 [9.6341246e-09 2.0976263e-08 1.0000000e+00]
 [9.0090362e-09 1.0000000e+00 7.8858063e-13]
 [1.2577500e-07 9.9999988e-01 1.1317461e-12]
 [1.6517433e-07 9.9999988e-01 6.4124053e-11]
 [9.9998689e-01 8.6301270e-06 4.5762977e-06]
 [2.2480985e-07 2.2176029e-04 9.9977797e-01]
 [3.7311970e-06 3.0532179e-02 9.6946412e-01]
 [6.8022232e-03 9.9293160e-01 2.6615566e-04]
 [9.9999988e-01 4.9391737e-08 1.7431600e-07]
 [9.9999893e-01 3.5537576e-07 7.4139950e-07]
 [9.9999976e-01 1.2220107e-07 6.1642304e-08]
 [1.4217401e-09 5.5738280e-07 9.9999940e-01]]
