In [1]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior() # 텐서플로우 버전 1로 낮추기 (버전 2 기능 사용불가하게 만들기)

Instructions for updating:
non-resource variables are not supported in the long term


In [ ]:
"""
자연어 처리를 위한 라이브러리 설치
1) 텐서플로우
2) 케라스
3) 젠심
4) 사이킷런
5) nltk (영문자연어처리) -> nltk.download
6) konlpy
7) jpype
* 설치된 라이브러리 확인 : pip list
"""

In [3]:
from nltk.tokenize import word_tokenize

print(word_tokenize("Don't be fooled by the dark sounding name, Mr. Jone's Orphanage is as cheery as cheery goes for a pastery shop."))

['Do', "n't", 'be', 'fooled', 'by', 'the', 'dark', 'sounding', 'name', ',', 'Mr.', 'Jone', "'s", 'Orphanage', 'is', 'as', 'cheery', 'as', 'cheery', 'goes', 'for', 'a', 'pastery', 'shop', '.']


In [4]:
from nltk.tokenize import WordPunctTokenizer

print(WordPunctTokenizer().tokenize("Don't be fooled by the dark sounding name, Mr. Jone's Orphanage is as cheery as cheery goes for a pastery shop."))

['Don', "'", 't', 'be', 'fooled', 'by', 'the', 'dark', 'sounding', 'name', ',', 'Mr', '.', 'Jone', "'", 's', 'Orphanage', 'is', 'as', 'cheery', 'as', 'cheery', 'goes', 'for', 'a', 'pastery', 'shop', '.']


In [6]:
from tensorflow.keras.preprocessing.text import text_to_word_sequence

print(text_to_word_sequence("Don't be fooled by the dark sounding name, Mr. Jone's Orphanage is as cheery as cheery goes for a pastery shop."))

["don't", 'be', 'fooled', 'by', 'the', 'dark', 'sounding', 'name', 'mr', "jone's", 'orphanage', 'is', 'as', 'cheery', 'as', 'cheery', 'goes', 'for', 'a', 'pastery', 'shop']


In [8]:
# 문장 토큰화
text1 = "I am actively looking for Ph.D. students. and you are a Ph.D student."
text2 = "His barber kept his word. But keeping such a huge secret to himself was driving him crazy. Finally, the barber went up a mountain and almost to the edge of a cliff. He dug a hole in the midst of some reeds. He looked about, to mae sure no one was near."

In [10]:
from nltk.tokenize import sent_tokenize
sent_tokenize(text1)
sent_tokenize(text2)

['His barber kept his word.',
 'But keeping such a huge secret to himself was driving him crazy.',
 'Finally, the barber went up a mountain and almost to the edge of a cliff.',
 'He dug a hole in the midst of some reeds.',
 'He looked about, to mae sure no one was near.']

In [14]:
from nltk.tokenize import word_tokenize
from nltk.tag import pos_tag #품사확인

imsi = word_tokenize(text1)
pos_tag(imsi)

[('I', 'PRP'),
 ('am', 'VBP'),
 ('actively', 'RB'),
 ('looking', 'VBG'),
 ('for', 'IN'),
 ('Ph.D.', 'NNP'),
 ('students', 'NNS'),
 ('.', '.'),
 ('and', 'CC'),
 ('you', 'PRP'),
 ('are', 'VBP'),
 ('a', 'DT'),
 ('Ph.D', 'NNP'),
 ('student', 'NN'),
 ('.', '.')]

In [18]:
from konlpy.tag import Okt # 옛날 Twitter 클래스

okt = Okt()
okt.morphs("열심히 공부한 우리, 취업에 성공합시다") #형태소 추출
okt.pos("열심히 공부한 우리, 취업에 성공합시다") #품사
okt.nouns("열심히 공부한 우리, 취업에 성공합시다") #명사 추출

['공부', '우리', '취업']

In [23]:
# 어간추출(stem, 의미), 접사(부가적인 의미)
# dogs dog(어간) -s(접사)

from nltk.stem import WordNetLemmatizer
wn = WordNetLemmatizer() #표제어 추출 (품사정보유지)
words = ['loves','dies','complete']
print(wn.lemmatize(words[2]))

from nltk.stem import PorterStemmer
ps = PorterStemmer() #어간추출 (품사정보상실)
ps.stem(words[2])

complete


'complet'

In [35]:
from nltk.corpus import stopwords
print(stopwords.words('english'))
ex = "Family is not an important thing. It's everything."
imsi = word_tokenize(ex)

result = []
for i in imsi:
    if i not in stopwords.words('english'):
        result.append(i)

print(result)

['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're", "you've", "you'll", "you'd", 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', "she's", 'her', 'hers', 'herself', 'it', "it's", 'its', 'itself', 'they', 'them', 'their', 'theirs', 'themselves', 'what', 'which', 'who', 'whom', 'this', 'that', "that'll", 'these', 'those', 'am', 'is', 'are', 'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had', 'having', 'do', 'does', 'did', 'doing', 'a', 'an', 'the', 'and', 'but', 'if', 'or', 'because', 'as', 'until', 'while', 'of', 'at', 'by', 'for', 'with', 'about', 'against', 'between', 'into', 'through', 'during', 'before', 'after', 'above', 'below', 'to', 'from', 'up', 'down', 'in', 'out', 'on', 'off', 'over', 'under', 'again', 'further', 'then', 'once', 'here', 'there', 'when', 'where', 'why', 'how', 'all', 'any', 'both', 'each', 'few', 'more', 'most', 'other', 'some', 'such', 'no', 'nor', 'not', 'only', 'own', 'same', 'so', 'than', '

In [ ]:
# https://www.ranks.nl/stopwords/korean

In [36]:
from nltk.tokenize import RegexpTokenizer #정규표현식 토크나이저
tok = RegexpTokenizer('[\w]+') #\w = [a-zA-Z0-9]
print(tok.tokenize(ex))

['Family', 'is', 'not', 'an', 'important', 'thing', 'It', 's', 'everything']


In [38]:
text = "A barber is a person. a barber is good person. a barber is huge person. he Knew A Secret! The Secret He Kept is huge secret. Huge secret. His barber kept his word. a barber kept his word. His barber kept his secret. But keeping and keeping such a huge secret to himself was driving the barber crazy. the barber went up a huge mountain."

In [39]:
text = sent_tokenize(text)
print(text)

['A barber is a person.', 'a barber is good person.', 'a barber is huge person.', 'he Knew A Secret!', 'The Secret He Kept is huge secret.', 'Huge secret.', 'His barber kept his word.', 'a barber kept his word.', 'His barber kept his secret.', 'But keeping and keeping such a huge secret to himself was driving the barber crazy.', 'the barber went up a huge mountain.']


In [41]:
len('love')

4

In [72]:
# len(text) # 11개의 문장 각각에 대해 단어토큰화 수행
# 1) 불용어 제거
# 2) 단어길이가 2 이하면 제거
# 3) 모든 단어는 소문자화

vocab = {}
mylist = []

for i in text:
    j = text_to_word_sequence(i)
    sent = []
    for k in j:
        if k not in stopwords.words('english'):
            if len(k)>2:
                sent.append(k)
                if k not in vocab:
                    vocab[k] = 0
                vocab[k] += 1
    mylist.append(sent)

In [74]:
print(mylist)
print(vocab)

[['barber', 'person'], ['barber', 'good', 'person'], ['barber', 'huge', 'person'], ['knew', 'secret'], ['secret', 'kept', 'huge', 'secret'], ['huge', 'secret'], ['barber', 'kept', 'word'], ['barber', 'kept', 'word'], ['barber', 'kept', 'secret'], ['keeping', 'keeping', 'huge', 'secret', 'driving', 'barber', 'crazy'], ['barber', 'went', 'huge', 'mountain']]
{'barber': 8, 'person': 3, 'good': 1, 'huge': 5, 'knew': 1, 'secret': 6, 'kept': 4, 'word': 2, 'keeping': 2, 'driving': 1, 'crazy': 1, 'went': 1, 'mountain': 1}


In [70]:
vs = sorted(vocab.items(), key=lambda x:x[1] , reverse=True)

In [71]:
vs

[('barber', 8),
 ('secret', 6),
 ('huge', 5),
 ('kept', 4),
 ('person', 3),
 ('word', 2),
 ('keeping', 2),
 ('good', 1),
 ('knew', 1),
 ('driving', 1),
 ('crazy', 1),
 ('went', 1),
 ('mountain', 1)]

In [78]:
wti = {}
i = 0

for word,f in vs:
    if f > 1 : # 단어빈도가 2 이상인 경우
        i += 1
        wti[word] = i

print(wti)

{'barber': 1, 'secret': 2, 'huge': 3, 'kept': 4, 'person': 5, 'word': 6, 'keeping': 7}


In [80]:
token = okt.morphs("오전에는 졸았지만, 오후에는 열심히 하겠다")

In [82]:
# 토큰 단위로 딕셔너리에 저장
word2index = {}
for v in token:
    # v 토큰이 word2index에 없다면
    if v not in word2index.keys():
        word2index[v] = len(word2index)

print(word2index) # 각 형태소에 인덱스 부여

{'오전': 0, '에는': 1, '졸았지만': 2, ',': 3, '오후': 4, '열심히': 5, '하겠다': 6}


In [87]:
def ohe1(w,word2index):
    arr = []
    for i in word2index.keys():
        if w==i:
            arr.append(1)
        arr.append(0)
    return arr

print(ohe1('오후', word2index))

[0, 0, 0, 0, 1, 0, 0, 0]


In [83]:
def ohe(w,word2index):
    ohv = [0]*len(word2index)
    idx = word2index[w]
    ohv[idx] = 1
    return ohv
print(ohe('오후', word2index))

[0, 0, 0, 0, 1, 0, 0]


In [86]:
from keras.preprocessing.text import Tokenizer
from keras.utils import to_categorical

text = """나랑 막걸리 마시러 갈래 안주는 파전 갈래 갈래 파전 최고야"""

t = Tokenizer()
t.fit_on_texts([text])
print(t)

In [96]:
t.word_index # 가장 많이 등장한 단어부터 역순으로 출력
t.index_word

{1: '갈래', 2: '파전', 3: '나랑', 4: '막걸리', 5: '마시러', 6: '안주는', 7: '최고야'}

In [101]:
enc = t.texts_to_sequences(['술 마시러 갈래 갈꺼야 말꺼야 갈래'])[0] # 코퍼스에 존재하는 단어의 인덱스 출력
to_categorical(enc) # 원핫인코딩

array([[0., 0., 0., 0., 0., 1.],
       [0., 1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.]], dtype=float32)

In [113]:
# bag of words : 각 단어에 인덱스 부여 -> 등장횟수 저장
import re

# 정규표현식과 sub로 마침표 없애기
token = re.sub("[.]","", "정부가 발표하는 물가상승률과 소비자가 느끼는 물가상승률은 다르다.")
# token = re.sub("(\.)","", "정부가 발표하는 물가 상승률과 소비자가 느끼는 물가상승률은 다르다.")
token
# re.sub(패턴,교체문자,데이터)
# re.sub("대한민국","한국","대한민국 우리나라")

'정부가 발표하는 물가상승률과 소비자가 느끼는 물가상승률은 다르다'

'정부가 발표하는 물가 상승률과 소비자가 느끼는 물가상승률은 다르다'

In [114]:
token = okt.morphs(token)
token

['정부', '가', '발표', '하는', '물가상승률', '과', '소비자', '가', '느끼는', '물가상승률', '은', '다르다']

In [117]:
bow = []
word2index = {}
for v in token:
    if v not in word2index.keys():
        word2index[v] = len(word2index)
        bow.insert(len(word2index)-1,1) #0으로 각 자리를 초기화
    else:
        idx = word2index.get(v)
        bow[idx] += 1
        # print(word2index)
        # print("="*50)
print(word2index)
print(bow)

{'정부': 0, '가': 1, '발표': 2, '하는': 3, '물가상승률': 4, '과': 5, '소비자': 6, '느끼는': 7, '은': 8, '다르다': 9}
[1, 2, 1, 1, 2, 1, 1, 1, 1, 1]


In [120]:
from sklearn.feature_extraction.text import CountVectorizer

corpus = ['you know I want your love. because I love you.']
#vec = CountVectorizer()
vec = CountVectorizer(stop_words=['love'])
# 각 단어의 빈도수
vec.fit_transform(corpus).toarray()
# 각 단어의 인덱스
print(vec.vocabulary_)

{'you': 3, 'know': 1, 'want': 2, 'your': 4, 'because': 0}


In [122]:
from math import log

docs = [
    '먹고 싶은 사과',
    '먹고 싶은 바나나',
    '길고 노란 바나나 바나나',
    '저는 과일이 좋아요'
]

voc = list(set(w for doc in docs for w in doc.split()))
voc

['바나나', '노란', '좋아요', '사과', '싶은', '과일이', '길고', '먹고', '저는']

In [126]:
voc.sort()
voc

['과일이', '길고', '노란', '먹고', '바나나', '사과', '싶은', '저는', '좋아요']

In [129]:
# TFIDF

n = len(docs)
def tfv(t,d):
    return d.count(t) # d문서 내에서 t단어의 등장 횟수
def idf(t):
    df=0
    for doc in docs:
        df += t in doc
    return log(n/(df+1))
def tfidf(t,d):
    return tfv(t,d)*idf(t)

In [ ]:
"""DTM 구현"""
#   과일이...
#1      0
#2      0
#3      1
#4      0

In [132]:
import pandas as pd

res = []
for i in range(n):
    res.append([])
    d = docs[i]
    for j in range(len(voc)):
        t = voc[j]
        res[-1].append(tfv(t,d))
mytf = pd.DataFrame(res,columns=voc)
mytf

과일이  길고  노란  먹고  바나나  사과  싶은  저는  좋아요
0    0   0   0   1    0   1   1   0    0
1    0   0   0   1    1   0   1   0    0
2    0   1   1   0    2   0   0   0    0
3    1   0   0   0    0   0   0   1    1

In [138]:
# 각 단어에 대한 idf를 출력
res = []
for j in range(len(voc)):
    t = voc[j]
    res.append(idf(t))
idf_ = pd.DataFrame(res,index=voc, columns = ['IDF'])
idf_

IDF
과일이  0.693147
길고   0.693147
노란   0.693147
먹고   0.287682
바나나  0.287682
사과   0.693147
싶은   0.287682
저는   0.693147
좋아요  0.693147

In [141]:
res = []
for i in range(n):
    res.append([])
    d = docs[i]
    for j in range(len(voc)):
        t = voc[j]
        res[-1].append(tfidf(t,d))

mytfidf = pd.DataFrame(res, columns = voc)
mytfidf

과일이        길고        노란        먹고       바나나        사과        싶은  \
0  0.000000  0.000000  0.000000  0.287682  0.000000  0.693147  0.287682   
1  0.000000  0.000000  0.000000  0.287682  0.287682  0.000000  0.287682   
2  0.000000  0.693147  0.693147  0.000000  0.575364  0.000000  0.000000   
3  0.693147  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   

         저는       좋아요  
0  0.000000  0.000000  
1  0.000000  0.000000  
2  0.000000  0.000000  
3  0.693147  0.693147

In [143]:
############### 여기까진 지우개로 지우세요 #################

corpus = [
    "you know i want you love",
    "I like you",
    "what should I do"
]

# DTM
from sklearn.feature_extraction.text import CountVectorizer
vector = CountVectorizer()
print(vector.fit_transform(corpus).toarray()) #tf
print(vector.vocabulary_)

[[0 1 0 1 0 1 0 2]
 [0 0 1 0 0 0 0 1]
 [1 0 0 0 1 0 1 0]]
{'you': 7, 'know': 1, 'want': 5, 'love': 3, 'like': 2, 'what': 6, 'should': 4, 'do': 0}


In [148]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidfv = TfidfVectorizer().fit(corpus)
a = tfidfv.transform(corpus).toarray()
pd.DataFrame(a, columns = sorted(tfidfv.vocabulary_.keys()))

do      know      like      love   should      want     what       you
0  0.00000  0.433816  0.000000  0.433816  0.00000  0.433816  0.00000  0.659857
1  0.00000  0.000000  0.795961  0.000000  0.00000  0.000000  0.00000  0.605349
2  0.57735  0.000000  0.000000  0.000000  0.57735  0.000000  0.57735  0.000000