In [4]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior() # 텐서플로우 버전 1로 낮추기 (버전 2 기능 사용불가하게 만들기)

Instructions for updating:
non-resource variables are not supported in the long term


In [5]:
# 허접한 동물 분류기
import numpy as np
# 포유류? 조류? 기타? 분류기 (신경망)
# 기준 - 털, 날개유무에 따라 분류
# [털,날개]
xdata = np.array(
    [[0,0],
    [1,0],
    [1,1],
    [0,0],
    [0,0],
    [0,1]
    ]
)

ydata = np.array(
    [[1,0,0], #기타
    [0,1,0], #포유류
    [0,0,1], #조류
    [1,0,0],
    [1,0,0],
    [0,0,1]
    ]
)

In [19]:
# 신경망 모델 구성

x = tf.placeholder(tf.float32, shape=[None,2])
y = tf.placeholder(tf.float32, shape=[None,3])

w = tf.Variable(tf.random_uniform([2,3],-1.,1.))
b = tf.Variable(tf.zeros([3])) # 분류기의 갯수

L = tf.add(tf.matmul(x,w),b) # [None,3]와 [3]요소간 덧셈 # L은 scores(logits)
L = tf.nn.relu(L) # relu 함수는 음수가 전달되는 경우에는 0, 양수가 전달되는 경우 그대로 리턴

# 예) scores = [8.05, 2.07, 1.3]
model = tf.nn.softmax(L) # 신경망모델

cost = tf.reduce_mean(-tf.reduce_sum(y*tf.log(model),axis=1))
train = tf.train.GradientDescentOptimizer(0.01).minimize(cost)

In [20]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())

In [132]:
# for step in range(2001):
#     sess.run(train, feed_dict= {x:xdata, y:ydata})
#     if step%100==0:
#         print(step, sess.run(cost, feed_dict= {x:xdata, y:ydata}))

print(sess.run(model, feed_dict={x:xdata}))
prediction = tf.argmax(model,axis=1) # 최댓값의 인덱스 추출
target = tf.arg_max(y,1)
print("예측값 : ", sess.run(prediction, feed_dict={x:xdata}))
print("실제값 : ", sess.run(target, feed_dict={y:ydata}))

isCorrect = tf.equal(prediction, target)
acc = tf.reduce_mean(tf.cast(isCorrect,tf.float32))
print("정확도 : %.2f" %sess.run(acc*100, feed_dict= {x:xdata, y:ydata}))

[[0.33333334 0.33333334 0.33333334]
 [0.33333334 0.33333334 0.33333334]
 [0.01078096 0.01078096 0.97843814]
 [0.33333334 0.33333334 0.33333334]
 [0.33333334 0.33333334 0.33333334]
 [0.0107819  0.0107819  0.9784362 ]]
예측값 :  [0 0 2 0 0 2]
실제값 :  [0 1 2 0 0 2]
정확도 : 83.33


In [155]:
# 딥러닝 모델구성
xdata = np.array(
[[0,0],
 [1,0],
 [1,1],
 [0,0],
 [0,0],
 [0,1],
]
)
ydata = np.array(
[[1,0,0], #기타
 [0,1,0], #포유류
 [0,0,1],#조류
 [1,0,0],
 [1,0,0],
 [0,0,1],
]
)

In [156]:
x=tf.placeholder(tf.float32,shape=[None,2])
y=tf.placeholder(tf.float32,shape=[None,3]) # 분류기가 3개(기타,포유류,조류)니까 3이에요.(한개만 1, 나머지는 0으로 출력)
w1=tf.Variable(tf.random_uniform([2,10],-1.,1.))
w2=tf.Variable(tf.random_uniform([10,3],-1.,1.)) #신경망은 2차원[입력층(특성),출력층(레이블)]
b1=tf.Variable(tf.zeros([10]))
b2=tf.Variable(tf.zeros([3]))

In [157]:
L1 = tf.add(tf.matmul(x,w1),b1)
L1 = tf.nn.relu(L1)
model =tf.add(tf.matmul(L1,w2),b2)
cost = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits_v2(labels=y , logits = model))
train = tf.train.AdamOptimizer(0.0001).minimize(cost)

In [160]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())

for step in range(3001):
    sess.run(train, feed_dict= {x:xdata, y:ydata})
    if step%1000==0:
        print(step, sess.run(cost, feed_dict= {x:xdata, y:ydata}))

0 1.327187
1000 1.0306166
2000 0.7625003
3000 0.5483403


In [161]:
print(sess.run(model, feed_dict={x:xdata}))
prediction = tf.argmax(model,axis=1) # 최댓값의 인덱스 추출
target = tf.arg_max(y,1)
print("예측값 : ", sess.run(prediction, feed_dict={x:xdata}))
print("실제값 : ", sess.run(target, feed_dict={y:ydata}))

isCorrect = tf.equal(prediction, target)
acc = tf.reduce_mean(tf.cast(isCorrect,tf.float32))
print("정확도 : %.2f" %sess.run(acc*100, feed_dict= {x:xdata, y:ydata}))

[[ 0.54620576 -0.56712973 -0.18317507]
 [-0.69633055  0.42157125 -0.8376914 ]
 [-1.3859531  -1.5791155  -0.55016565]
 [ 0.54620576 -0.56712973 -0.18317507]
 [ 0.54620576 -0.56712973 -0.18317507]
 [-1.0008302  -2.4590168  -0.22513123]]
예측값 :  [0 1 2 0 0 2]
실제값 :  [0 1 2 0 0 2]
정확도 : 100.00
